### ISSUE TITLE
Questions about fastmove in userspace

### ISSUE THREAD

**Issue by xywoo-cs** [fastmove-open/fastmove#1]
This is a very interesting job! I am particularly interested in DMA part.   

I have noticed that the benchmarks for fastmove seem to revolve around kernel FS, so it modified the kernel to implement `fm_copy_from_user()` and `fm_copy_to_user()`. But I'm curious about how I can reference this artifact if all I need is to simply move data between two addresses in userspace?

Thank you in advance!

**Comment by hellobbn** [comment]
Hi, Thanks for you interest in our project!

Our implementation is not suitable for moving data between two addresses in DRAM considering the following two problems:

1. The address in both source and destination might not reside in DRAM, meaning that we will need to pin the address in both source and destination, which incurs higher overhead
2. The physical address in both source and destination will not be contiguous, so there will be twice more descriptors submitted, which would cause higher submission time and decrease performance.

So it might not be ideal to use I/OAT to move data between two DRAM addresses in userspace. However, we do recommend using the newer Intel DSA to do that, because the DSA hardware supports the PCI Express Address Translation Service (ATS) and Page Request Service (PRS) capabilities.

Thanks!

**Comment by xywoo-cs** [comment]
Thank you for your response!  
In order to avoid X-Y problems, I'd like to express my questions more clearly.

1. I'm still concerned about **moving data from NVM address to DRAM**, even though in userspace.
2. My scenario is more like _HeMem focusing on smaller objects_, or _FastMove paying attention to asynchronous operations in userspace_. **So does FastMove have an `fm_memcpy()` equivalent to `memcpy()`?**
3. DSA should only be supported on specific platforms, and it seems that these platforms currently do not support NVM devices. However, DSA should indeed be a fully evolved version of DMA, and I'm also curious about the performance differences between them.

**Comment by hellobbn** [comment]
Thanks for your reply!

1. No, we don't provide userspace interface for memcpy. That said, we suggest using SPDK, which could be a better fit.
2. Regarding the DSA performance, I suggest reading this paper on Arxiv: https://arxiv.org/abs/2305.02480

Thanks!

**Comment by xywoo-cs** [comment]
Thank you sincerely once again for your response!
